import type { Metadata } from "next";
import "./globals.css";
import { FavoritesProvider } from "./context/FavoritesContext";
import { CartProvider } from "./context/CartContext";

export const metadata: Metadata = {
  title: "Plan Care",
  description: "Generated by create next app",
  icons:{
    icon:"/icon.png"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <FavoritesProvider>
          <CartProvider>
            {children}
          </CartProvider>
           
        </FavoritesProvider>

       
      </body>
    </html>
  );
}
//git push -f origin main
//git push -u origin main perche -u collega main(local) al origin(github)